### ISSUE TITLE
Request for Assistance with Unreasonable Data in Vehicle Routing Problem (VRP) Request

### ISSUE THREAD

**Issue by Mani-java-dev** [VROOM-Project/vroom#1206]
Hello Community,

I hope you're doing well.

I have a question regarding a Vehicle Routing Problem (VRP) request I made, and I would appreciate any guidance you could offer. Here is the structure of my request:

`Request :
 
{

  "vehicles": [

    {

      "id": 1,

      "start": [103.85472186649208, 1.3121504670878485],

      "capacity": [20],

      "time_window": [28800, 64800] 

    }

  ],

  "shipments": [

    {

      "id": 1,

      "pickup": {

        "id": 1, 

        "location": [103.85472186649208, 1.3121504670878485],

        "time_windows": [[32400, 32700]]

      },

      "delivery": {

        "id": 1, 

        "location": [103.82381712150872, 1.2541995275305768]

      },

       "amount": [5]

    },

    {

      "id": 2,

      "pickup": {

        "id": 2, 

        "location": [103.85581519717888, 1.3109139932131373],

        "time_windows": [[32700, 33000]]

      },

      "delivery": {

        "id": 2, 

        "location": [103.82381712150872, 1.2541995275305768]

      },

       "amount": [4]

    },

    {

      "id": 3,

      "pickup": {

        "id": 3, 

        "location": [103.85581519717888, 1.3109139932131373],

        "time_windows": [[32700, 33000]]

      },

      "delivery": {

        "id": 3, 

        "location": [103.82381712150872, 1.2541995275305768]

      },

       "amount": [4]

    }

  ]

}
 `
I have noticed that every time I make the same request, I receive a different response, but the data still seems unrealistic. Specifically, the shipment routes, times, and distances do not seem to match the expected real-world constraints.

Could anyone please suggest what might be causing this issue? Are there any common pitfalls or adjustments I should consider in my request to get more realistic data?

Thank you so much for your help and insights!

**Comment by jcoupey** [comment]
> every time I make the same request, I receive a different response

That is weird, can you expand on your setup? Where/how are you making requests?

> the shipment routes, times, and distances do not seem to match the expected real-world constraints

Again please be more specific on what exactly is the problem?

**Comment by MonishK2002** [comment]
@jcoupey That is weird, can you expand on your setup? Where/how are you making requests?
 
I am using a docker-compose.yml to define my VROOM and OSRM services  and running them on their default ports.
 
Docker compose:
 
```
version: '3.8'
 
services:
  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    volumes:
      - ./data:/data
      - ./data/car-copy.lua:/opt/bus.lua # Mount bus.lua to the correct path
    command: >
      sh -c "osrm-extract -p /opt/bus.lua /data/${OSRM_PBF} &&
             osrm-contract /data/${OSRM_PBF_BASE}.osrm &&
             osrm-routed --max-table-size=1000 /data/${OSRM_PBF_BASE}.osrm"
    environment:
      - OSRM_PBF=malaysia-singapore-brunei-latest.osm.pbf
      - OSRM_PBF_BASE=malaysia-singapore-brunei-latest
    ports:
      - "5000:5000"
 
  vroom:
    image: vroomvrp/vroom-docker:v1.14.0-rc.2
    container_name: vroom
    volumes:
      - ./vroom-conf:/conf
    depends_on:
      - osrm
    environment:
      - VROOM_ROUTER=osrm
    ports:
      - "3000:3000"
```
 
 
And I am testing the VROOM endpoint with the VRP problem by making requests via Postman API client.
 
I have a problem of automating the trips assignments to vehicles based on certain rules and constraints.
Each trip is modelled after real world transportation of passengers from a source to a destination. I am converting my trip model to VROOM shipment model (comprising of a pickup and delivery). I am calculating the distance/duration values based on lat,lng coordinates of source and destination from Google Maps API and using it to set the time-windows on the pickup and delivery shipment steps. 
 
Certain type of trips can be handled only by certain vehicles. Is there any way to accommodate this as hard constraint in the VROOM shipment-vehicle model other than setting the same value for skill in both vehicle and shipment model and expecting them to match-up?
 
My main concern in how to accurately define my constraints, namely the capacity and time constraint as hard constraints (trip start and end time windows should be respected) into the VROOM request model?

[Vroom_Request_Response.json](https://github.com/user-attachments/files/18161740/Vroom_Request_Response.json)

In the above document you can see that a single request yields multiple responses. Additionally some data are unrealistic such as a duration of 1 minute for a 1 km distance Could you please assist in resolving these discrepancies
