### ISSUE TITLE
Ability to add remote matrix providers

### ISSUE THREAD

**Issue by nilsnolde** [VROOM-Project/vroom#219]
Ref. #218. 

To be able to run `vroom` locally, but use a remote `matrix` provider, such as Mapbox or openrouteservice, we'd have to be able to:

1. specify a host-dependent endpoint name, e.g. `table` for OSRM local, `matrix-service` for Mapbox OSRM remote, which could also contain a host dependent slug, e.g. ORS local is `http://localhost/ors/matrix`, remote API is `https://api.openrouteservice.org/matrix`
2. set an API key for these services 

In this spirirt, what do you think about YAML or INI for configs? E.g.
```yaml
osrm:
  local:
    name: /table
    profiles:
      car:
        host: 0.0.0.0
        port: 8080
  mapbox:
    name: /matrix-service
    key: my_key
    profiles:
      car:
        host: https://api.mapbox.com
        port: 80
ors:
  local:
    name: /ors/matrix
  ...
```
Might be easier for people to keep track of all options and wouldn't clutter the args list so much. Basically, one would have to only specify the router, provider and profile, the rest would be in the config. Not sure how much work that refactoring would be though..
