### ISSUE TITLE
option -c causing unassigned

### ISSUE THREAD

**Issue by Shooter533** [VROOM-Project/vroom#736]
I have recently deployed a new vroom stack with docker using OSRM with Australian OSM Map backend.
I can successfully run and get a result in the default solving mode, however, if I use option -c the run in plan mode it will always return the jobs unassigned.

I have tried using the same input json on the demo server http://solver.vroom-project.org and got the desired result, eta's etc.
My docker-compose
```
version: "2.4"
services:
  vroom:
    network_mode: host
    image: vroomvrp/vroom-docker:v1.12.0
    container_name: vroom
    volumes:
      - ./vroom-conf/:/conf
    environment:
      - VROOM_ROUTER=osrm  # router to use, osrm, valhalla or ors
    depends_on:
      - osrm
  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ${PWD}:/data
    command: "osrm-routed --max-matching-size 1000 --max-table-size 1000 --max-viaroute-size 1000 --algorithm mld /data/australia-latest.osrm"
```
