### ISSUE TITLE
strange (too long) route created by VRoom

### ISSUE THREAD

**Issue by twarogowski-dts** [VROOM-Project/vroom#773]
Hello,

first I want to thank you for a fantastic work on VRoom project. It is a truly great tool, which produces impressive results. Most of the time it gives consistent results, often better than those created by human planner. However, I just noticed one recent anomaly that I cannot explain. Result contains several routes, the weird one is the one with distance 461539 meters. All jobs in this route have same time_windows, so I cannot tell why the route is so long. This result was easily manually post-optimized by my colleague by simply rearranging order of jobs, resulting in distance of 339 km, instead of 461. 

[vroom_request_1.json.txt](https://github.com/VROOM-Project/vroom/files/9449944/vroom_request_1.json.txt)
[vroom_response_1.json.txt](https://github.com/VROOM-Project/vroom/files/9449945/vroom_response_1.json.txt)

**Comment by jcoupey** [comment]
Thanks for reporting and sharing an instance. The response you provide does not contain the full optimization output (only the `routes` array), can you please also share the full response?

**Comment by twarogowski-dts** [comment]
Sure, I did not turn off results filtering in Insomnia REST App :)

[vroom_response_1_full.json.txt](https://github.com/VROOM-Project/vroom/files/9452171/vroom_response_1_full.json.txt)

**Comment by jcoupey** [comment]
Thanks, this route does indeed look weird. In order to reproduce the problem, could you please share:
- `vroom` version;
- specific tuning (e.g. `-x` command-line flag) if any;
- a [standalone version](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance) of the problem instance.

**Comment by twarogowski-dts** [comment]
Sure:

I use vroom v1.11
no specific tuning, I use standard docker compose:

```
version: "3.7"

networks:
  geonet:
    external: true

services:
  vroom_osrm:
    image: vroomvrp/vroom-docker:v1.11.0
    container_name: vroom_osrm
    restart: unless-stopped
    volumes:
      - /opt/geo/vroom_osrm/conf/:/conf
      # ports:
      # - 3000:3000
    environment:
      - VROOM_ROUTER=osrm
    networks:
      - geonet
```

and this is my conf (part of it):

```
cliArgs:
  geometry: false # retrieve geometry (-g)
  threads: 4 # number of threads to use (-t)
  explore: 5 # exploration level to use (0..5) (-x)
  limit: "1mb" # max request size
  logdir: "/.." # the path for the logs relative to ./src
  logsize: "10M"
  maxlocations: 1000 # max number of jobs/shipments locations
  maxvehicles: 200 # max number of vehicles
  override: true # allow cli options override (-g, -t and -x)
  path: "" # VROOM path (if not in $PATH)
  port: 3000 # expressjs port
  router: "osrm" # routing backend (osrm, libosrm or ors)
  timeout: 300000 # milli-seconds
  baseurl: "/"
```

here you have request with matrices in it:

[vroom_request_1_matrix.json.txt](https://github.com/VROOM-Project/vroom/files/9459489/vroom_request_1_matrix.json.txt)
